### ISSUE TITLE
NNJoin returning all "-1" or "0" values

### ISSUE THREAD

**Issue by jaymschoen** [havatv/qgisnnjoinplugin#19] opened 2019-02-25 19:04 UTC
I've been using NNJoin 3.1.1 in QGIS 2 and 3 to calculate distances from species presence/absence points (point or multipoint) to environmental features (point, line, multiline, polygon). It worked great for some time but now just returns all "-1" or "0" values for my entire vector. Even when I run it with the same input and join layers that worked in the past, I get this result. The issue only seems to occur when joining to multiline string objects and when I inspect the resulting layer, it looks like only one feature was selected to join (with a uniform distance of "-1" or "0").

Thanks in advance for your help!

**Comment by jaymschoen** [comment] 2019-02-25 21:16
I was able to get it working by converting any multipoint files to singlepoint, but I am still unsure what caused the issue as multipoint files had worked fine before. I also created a spatial index for my point shapefile, but am not sure if that made a difference. Thanks again for the plugin.

**Comment by havatv** [comment] 2019-02-26 00:29
Thank you for reporting, @jaymschoen!
The distance calculations in NNJoin rely on the QgsGeometry distance function (which uses the GEOS distance function) and the QgsSpatialIndex functions.  The index is built by the plugin.
I don't think presence or absence of a spatial index on the datasets should matter.
Could you share small sample datasets that demonstrate the issue?

**Comment by jaymschoen** [comment] 2019-02-26 18:13
Thanks for getting back! I’ve attached the main files I was trying to use the plugin for (a subset of generated pseudoabsences, PA 272 group 1, and a shapefile of the main roads in Paraguay, pyrutas_nuevo). I realize that there are several geometric errors in the main roads shapefile, but I still don’t understand why it worked before then stopped, and now seems to be working fine. The plugin is working great on singlepoint files that I am analyzing today…

Please let me know if I can provide anything else.

Cheers,
Jay

**Comment by havatv** [comment] 2019-02-26 20:01
@jaymschoen, in order to attach the files, you first need to zip them into a .zip archive and then drag and drop the .zip file into the box.

**Comment by jaymschoen** [comment] 2019-02-26 20:04
Sorry about that.



Jay

**Comment by havatv** [comment] 2019-02-27 07:12
Follow the link ("view it on github") at the bottom of the email to get to the github page where you can drag and drop the .zip file to add it to github.

**Comment by jaymschoen** [comment] 2019-03-02 20:07
I don’t have permission to share the main roads file publicly so I sent it here instead; is it possible for you to open it via email to analyze?

Thanks,
Jay

**Comment by havatv** [comment] 2019-03-03 00:14
Attachments do not seem to make it through github email. You can send directly to havard.tveite@nmbu.no.

**Comment by havatv** [comment] 2019-03-03 23:18
Thanks for sending me the sample data, @jaymschoen.
I could reproduce the behaviour you reported. The only way I could make it work with the current NNJoin version was to change both layers to singlepart ("Multipart to singleparts") before running NNJoin.
I will have to look into this.

**Comment by havatv** [comment] 2019-03-05 09:36
It turns out that the NNJoin code does not handle features with missing geometries. Should be possible to fix.

**Comment by havatv** [comment] 2019-03-05 11:32
Should be fixed now. Version 3.1.2 includes the fix and has been uploaded (and is available) on plugins.qgis.org.
Thank you for reporting, @jaymschoen ! Much appreciated. You can now test with the new version.

**Closed as completed** 2019-03-05 11:32 UTC
Labels: bug

**Comment by jaymschoen** [comment] 2019-03-05 14:53
My pleasure, thank you for your responsiveness and quick fix! Take care
